version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itexstore-container
    tty: true
    ports:
      - "9090:9090"
      # - "9091:9091"
      # - "9092:9092"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    volumes:
      - /opt/itexstore/itexstore_api/logs:/app/logs
      # - /Users/kennethosekhuemen/Projects/itex_store/itexstore_api/logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - hostnetwork

name: itexstore_api

networks:
  hostnetwork:
    driver: bridge