version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appstore-container
    tty: true
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    volumes:
      - /opt/appstore/appstore_api/logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - hostnetwork

name: appstore_api

networks:
  hostnetwork:
    driver: bridge
